version: '3.9'

services:
  prh-service:
    build:
      context: ./prh-service
      dockerfile: Dockerfile
    container_name: prh_service_backend
    restart: always
    ports:
      - "8888:8443"
      # - "8443:8443"
    environment:
      PRH_API_BASE_URL: https://avoindata.prh.fi/opendata-ytj-api/v3
      JAVA_OPTS: "-Xms256m -Xmx512m"

    volumes:
      - ./prh-service/keystore.p12:/app/keystore.p12

    networks:
      - prh-app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    ports:
      - "80:80"   
      - "443:443"
    depends_on:
      - prh-service
    networks:
      - prh-app-network

networks:
  prh-app-network:
    driver: bridge